In [128]:
import pandas as pd
import numpy as np
import sys
np.set_printoptions(threshold=sys.maxsize)

In [129]:
models = ["bongsoo", "kykim", "monologg", "snunlp", "xlm"]

In [130]:
model_output_dict = dict()
total_length = 1100
esnb = np.zeros((total_length, len(models)))

for model in models:
    model_output_dict[model] = pd.read_csv(f'./esnb_ingredients/output_{model}.csv')


for i in range(total_length):
    for j, model in enumerate(models):
        esnb[i, j] = model_output_dict[model]["target"][i]

In [131]:
esnb

array([[ 3.33740902e+00,  3.03694797e+00,  3.68976188e+00,
         3.30000000e+00,  3.31346703e+00],
       [ 4.31013060e+00,  4.36834288e+00,  4.58589077e+00,
         4.50000000e+00,  4.11767960e+00],
       [ 1.38518059e+00,  1.17344010e+00,  1.70982313e+00,
         1.90000000e+00,  9.47589099e-01],
       [ 2.53295191e-02,  1.06984884e-01,  4.91517186e-02,
         1.00000000e-01,  1.17895193e-01],
       [ 3.85622907e+00,  3.52505064e+00,  3.61294937e+00,
         3.80000000e+00,  4.07966709e+00],
       [ 3.38821077e+00,  2.90312123e+00,  2.81431723e+00,
         3.20000000e+00,  2.80291843e+00],
       [ 3.95216370e+00,  3.91380286e+00,  4.13136482e+00,
         4.20000000e+00,  4.33046389e+00],
       [ 1.66619217e+00,  1.56381881e+00,  1.86887693e+00,
         1.80000000e+00,  1.70743895e+00],
       [ 4.31427121e-01,  6.18311703e-01,  3.69270056e-01,
         5.00000000e-01,  4.82069999e-01],
       [ 5.21041584e+00,  5.13477755e+00,  5.00784063e+00,
         5.20000000e+00

In [132]:
esnb_result = np.zeros((total_length, 2))
esnb_std_mean_list = np.zeros((total_length, 2))
esnb_result

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.

In [133]:
for i in range(total_length):
    # esnb_result[i] = sum(esnb[i]) - max(esnb[i]) 
    esnb_std_mean_list[i, 0] = np.std(esnb[i])
    esnb_std_mean_list[i, 1] = np.mean(esnb[i])

In [134]:
for i in range(total_length):
    for j in range(len(models)):
        if abs(esnb[i, j] - esnb_std_mean_list[i, 1]) / esnb_std_mean_list[i, 0] < 1.04:
            esnb_result[i][0] += esnb[i, j]
            esnb_result[i][1] += 1

In [135]:
esnb_std_mean_list

array([[ 0.20803083,  3.33551718],
       [ 0.16158969,  4.37640877],
       [ 0.34627223,  1.42320658],
       [ 0.03606834,  0.07987226],
       [ 0.19430905,  3.77477923],
       [ 0.23283254,  3.02171353],
       [ 0.15522099,  4.10555905],
       [ 0.10583191,  1.72126537],
       [ 0.08264941,  0.48021578],
       [ 0.10273158,  5.17481617],
       [ 0.35024661,  1.58533049],
       [ 0.19132872,  2.58497616],
       [ 0.30561764,  3.12975948],
       [ 0.16038775,  2.16750302],
       [ 0.47269164,  1.35034437],
       [ 0.11899912,  4.30519283],
       [ 0.10976253,  5.00422327],
       [ 0.75319732,  2.57722959],
       [ 0.09347507,  5.21174685],
       [ 0.0534638 ,  4.40019541],
       [ 0.21039174,  2.8542717 ],
       [ 0.33840679,  2.44264325],
       [ 0.33982499,  2.02935071],
       [ 0.20902584,  0.88926295],
       [ 0.14753965,  1.5493385 ],
       [ 0.21216466,  2.23344151],
       [ 0.09618256,  1.30097744],
       [ 0.22867348,  1.25721869],
       [ 0.38856861,

In [137]:
esnb_result

array([[ 9.95087605,  3.        ],
       [13.17847347,  3.        ],
       [ 4.26844382,  3.        ],
       [ 0.2561366 ,  3.        ],
       [11.26917844,  3.        ],
       [11.72035689,  4.        ],
       [12.28352852,  3.        ],
       [ 5.17363112,  3.        ],
       [ 1.41349712,  3.        ],
       [15.54519339,  3.        ],
       [ 4.63391628,  3.        ],
       [ 4.99059153,  2.        ],
       [11.94472446,  4.        ],
       [ 6.54820213,  3.        ],
       [ 4.55172187,  4.        ],
       [12.98555365,  3.        ],
       [15.03976068,  3.        ],
       [11.75250492,  4.        ],
       [21.0263999 ,  4.        ],
       [13.1570797 ,  3.        ],
       [11.74778199,  4.        ],
       [10.43808813,  4.        ],
       [ 6.03799903,  3.        ],
       [ 3.93896961,  4.        ],
       [ 3.27770684,  2.        ],
       [ 6.83476491,  3.        ],
       [ 3.83715487,  3.        ],
       [ 2.20673931,  2.        ],
       [15.29294744,

In [148]:
esnb_result_final = np.zeros((total_length))
for i in range(total_length):
    esnb_result_final[i] = esnb_result[i][0] / esnb_result[i][1]

In [149]:
esnb_result_final

array([ 3.31695868,  4.39282449,  1.42281461,  0.08537887,  3.75639281,
        2.93008922,  4.09450951,  1.72454371,  0.47116571,  5.18173113,
        1.54463876,  2.49529576,  2.98618112,  2.18273404,  1.13793047,
        4.32851788,  5.01325356,  2.93812623,  5.25659997,  4.38569323,
        2.9369455 ,  2.60952203,  2.01266634,  0.9847424 ,  1.63885342,
        2.27825497,  1.27905162,  1.10336965,  3.82323686,  3.14259436,
        4.24661109,  1.07865105,  2.38260887,  2.95940466,  2.94326341,
        0.79207257,  3.35661256,  0.56241745,  1.43980967,  3.02736209,
        0.55668866,  3.87336421,  0.56994241,  1.42582637,  2.72471873,
        5.24809418,  2.05386893,  1.78148293,  0.35451205,  3.50813595,
        0.03260739,  1.80472528,  2.78588634,  3.08254329,  4.13386692,
        1.5207029 ,  3.73032118,  1.11374359,  2.45636725,  3.92548338,
        4.11786366,  3.73721504,  1.4682721 ,  1.80575168,  2.23555527,
        3.8014963 ,  2.95689416,  0.80131926,  2.49367476,  3.12

In [188]:
df = pd.DataFrame({"id": [f"boostcamp-sts-v1-test-{i:03}" for i in range(1100)],"target": esnb_result_final})

In [190]:
df

id    target
0      boostcamp-sts-v1-test-000  3.316959
1      boostcamp-sts-v1-test-001  4.392824
2      boostcamp-sts-v1-test-002  1.422815
3      boostcamp-sts-v1-test-003  0.085379
4      boostcamp-sts-v1-test-004  3.756393
...                          ...       ...
1095  boostcamp-sts-v1-test-1095  1.458563
1096  boostcamp-sts-v1-test-1096  4.178092
1097  boostcamp-sts-v1-test-1097  3.214610
1098  boostcamp-sts-v1-test-1098  3.734066
1099  boostcamp-sts-v1-test-1099  4.865113

[1100 rows x 2 columns]

In [191]:
df.to_csv('./my_esnb.csv', index=False)